=== ocsf/ocsf-schema/metaschema/common-event-object.schema.json
{
    "$id": "https://schema.ocsf.io/common-event-object.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Object",
    "description": "Common metaschema shared between objects and event classes.",
    "type": "object",
    "anyOf": [
        {
            "required": [
                "description",
                "caption",
                "name",
                "attributes"
            ]
        },
        {
            "required": [
                "extends"
            ]
        }
    ],
    "properties": {
        "@deprecated": {
            "$ref": "deprecated.schema.json"
        },
        "description": {
          "type": "string",
          "description": "A concise description of the object."
        },
        "caption": {
          "type": "string",
          "description": "A short, human friendly name for the object."
        },
        "name": {
          "type": "string",
          "description": "A name of the object. It must be a unique name. The name is all lower case letters, combine words using underscore.",
          "pattern": "^[a-z0-9_]*$"
        },
        "extends": {
            "type": "string",
            "description": "An object that this one extends from."
        },
        "constraints": {
            "type": "object",
            "description": "Constraints that apply to the attribute requirements.",
            "properties": {
                "at_least_one": {
                    "type": "array",
                    "items": {"type": "string"}
                },
                "just_one": {
                    "type": "array",
                    "items": {"type": "string"}
                }
            },
            "additionalProperties": false
        },
        "profiles": {
            "type": "array",
            "items": {"type": "string"},
            "description": "The list of profiles used to create the event."
        },
        "attributes": {
            "type": "object",
            "description": "A dictionary of attributes for the object.",
            "properties": {
                "$include": {
                    "description": "A reference to another schema for attributes to include.",
                    "type": "array",
                    "items": {
                        "type": "string",
                        "format": "uri-reference"
                    }
                }
            },
            "patternProperties": {
                "^[a-z0-9_]*$": {
                    "$ref": "attribute.schema.json"
                }
            },
            "additionalProperties": false
        }
    }
}

=== ocsf/ocsf-schema/extensions/archive/objects/resource.json
{
    "description": "The resource object describes a managed resource.",
    "caption": "Resource",
    "name": "resource",
    "attributes": {
        "account_uid": {
            "description": "The unique identifier of the resource owning account(e.g. AWS Account ID).",
            "requirement": "optional",
            "caption": "Account UID",
            "type": "string_t"
        },
        "cloud_partition": {
            "requirement": "optional",
            "caption": "Cloud Partition",
            "description": "The canonical cloud partition name to which the region is assigned (e.g. AWS Partitions: aws, aws-cn, aws-us-gov).",
            "type": "string_t"
        },
        "criticality": {
            "description": "The criticality of the resource.",
            "requirement": "optional",
            "caption": "Criticality",
            "type": "string_t"
        },
        "details": {
            "description": "The details pertaining to the resource.",
            "requirement": "optional",
            "caption": "Details",
            "type": "string_t"
        },
        "group_name": {
            "requirement": "recommended",
            "caption": "Group Name",
            "description": "The name of the group that the resource belongs to.",
            "type": "string_t"
        },
        "labels": {
            "requirement": "optional",
            "caption": "Labels",
            "description": "The list of labels attached to an event, object, or attribute.",
            "is_array": true,
            "type": "string_t"
        },
        "name": {
            "description": "The name of the resource.",
            "requirement": "recommended",
            "caption": "Name",
            "type": "string_t"
        },
        "owner": {
            "description": "The identity of the service or user account that owns the resource",
            "requirement": "recommended",
            "caption": "Owner",
            "type": "string_t"
        },
        "region": {
            "description": "The region of the resource.",
            "requirement": "optional",
            "caption": "Region",
            "type": "string_t"
        },
        "type": {
            "description": "The type of the resource.",
            "requirement": "optional",
            "caption": "Type",
            "type": "string_t"
        },
        "uid": {
            "description": "The unique identifier of the resource.",
            "requirement": "recommended",
            "caption": "Unique ID",
            "type": "string_t"
        },
        "raw_data": {
            "group": "context",
            "caption": "Raw Data",
            "description": "The event data as received from the event source.",
            "type": "json_t"
        },
        "record_id": {
            "description": "Unique identifier for the object",
            "group": "primary",
            "requirement": "required",
            "caption": "Record ID",
            "type": "string_t"
        }
    },
    "@deprecated": {
        "since": "1.1.0",
        "message": "Deprecated in upgrade from ocsf-0.31.1 to qdm-1.1.0"
    }
}

=== ocsf/ocsf-schema/objects/entity/image.json
{
  "caption": "Image",
  "name": "image",
  "description": "The Image object describes a specific Virtual Machine or Container image. Defined by D3FEND <a target='_blank' href='https://d3fend.mitre.org/dao/artifact/d3f:ContainerImage/'>d3f:ContainerImage</a>.",
  "extends": "entity",
  "attributes": {
    "labels": {
      "description": "The image labels.",
      "requirement": "optional"
    },
    "name": {
      "description": "The image name. For example: <code>elixir</code>."
    },
    "path": {
      "description": "The full path to the image file.",
      "requirement": "optional"
    },
    "tag": {
      "requirement": "optional"
    },
    "uid": {
      "description": "The unique image ID. For example: <code>77af4d6b9913</code>.",
      "requirement": "required"
    }
  },
  "constraints": {}
}

=== ocsf/ocsf-schema/objects/entity/endpoint/network_endpoint.json
{
  "caption": "Network Endpoint",
  "name": "network_endpoint",
  "extends": "endpoint",
  "description": "The network endpoint object describes source or destination of a network connection.",
  "attributes": {
    "intermediate_ips": {
      "requirement": "optional"
    },
    "port": {
      "description": "The port used for communication within the network connection.",
      "requirement": "recommended"
    },
    "svc_name": {
      "requirement": "recommended"
    }
  },
  "constraints": {
    "at_least_one": [
      "ip",
      "uid",
      "name",
      "hostname",
      "svc_name",
      "instance_uid",
      "interface_uid",
      "interface_name"
    ]
  }
}

=== ocsf/ocsf-schema/objects/startup_app.json
{
  "caption": "Startup Application",
  "name": "startup_app",
  "description": "The startup application object describes an application that has associated startup criteria and configurations.",
  "attributes": {
    "name": {
      "description": "The unique name of the startup application.",
      "requirement": "required"
    },
    "run_modes": {
      "description": "The list of run_modes, normalized to the captions of the run_mode_id values.  In the case of 'Other', they are defined by the event source.",
      "requirement": "optional"
    },
    "run_mode_ids": {
      "description": "The list of normalized identifiers that describe the startup applications' properties when it is running.  Use this field to capture extended information about the process, which may depend on the type of startup application.  E.g., A Windows service that interacts with the desktop.",
      "requirement": "optional",
      "enum": {
        "1": {
          "caption": "Interactive",
          "description": "The application interacts with the desktop."
        },
        "2": {
          "caption": "Own Process",
          "description": "The application runs in its own process."
        },
        "3": {
          "caption": "Shared Process",
          "description": "The application runs in a shared process."
        }
      }
    },
    "run_state": {
      "description": "The run state of the startup application.",
      "requirement": "optional"
    },
    "run_state_id": {
      "description": "The run state ID of the startup application.",
      "requirement": "recommended",
      "enum": {
        "1": {
          "caption": "Stopped",
          "description": "The sercie is not running."
        },
        "2": {
          "caption": "Start Pending",
          "description": "The service is starting."
        },
        "3": {
          "caption": "Stop Pending",
          "description": "The service is stopping."
        },
        "4": {
          "caption": "Running",
          "description": "The service is running."
        },
        "5": {
          "caption": "Continue Pending",
          "description": "The service is pending continue."
        },
        "6": {
          "caption": "Pause Pending",
          "description": "The service is pending pause."
        },
        "7": {
          "caption": "Paused",
          "description": "The service is paused."
        },
        "8": {
          "caption": "Restart Pending",
          "description": "The service is pending restart."
        }
      }
    },
    "start_type": {
      "description": "The start type of the startup application.",
      "requirement": "optional"
    },
    "start_type_id": {
      "description": "The start type ID of the startup application.",
      "requirement": "required"
    },
    "type": {
      "caption": "Type",
      "description": "The startup application type.",
      "requirement": "optional",
      "type": "string_t"
    },
    "type_id": {
      "caption": "Type ID",
      "description": "The startup application type identifier.",
      "requirement": "recommended",
      "enum": {
        "0": {
          "caption": "Unknown",
          "description": "The type is unknown."
        },
        "1": {
          "caption": "Kernel Mode Driver",
          "description": "Kernel mode driver."
        },
        "2": {
          "caption": "User Mode Driver",
          "description": "User mode driver."
        },
        "3": {
          "caption": "Service",
          "description": "A background process typically managed by the operating system, e.g., a service process on Windows or a systemd-managed daemon on Linux."
        },
        "4": {
          "caption": "User Mode Application",
          "description": "An application that runs in the user space."
        },
        "5": {
          "caption": "Autoload",
          "description": "The macOS Autoload Application."
        },
        "6": {
          "caption": "System Extension",
          "description": "System extensions on macOS enables 3rd parties to extend the capabilities of macOS."
        },
        "7": {
          "caption": "Kernel Extension",
          "description": "Kernel extensions on macOS includes Apple provided pre-installs and 3rd party installs which enables support for specific hardware or software features not natively supported by macOS."
        },
        "8": {
          "caption": "Scheduled Job, Task",
          "description": "A job or task that runs on a configured schedule."
        },
        "99": {
          "caption": "Other",
          "description": "The startup application type is not mapped. See the <code>type</code> attribute, which contains data source specific values."
        }
      },
      "type": "integer_t"
    },
    "driver": {
      "description": "The startup application kernel driver resource.",
      "requirement": "optional"
    },
    "job": {
      "description": "The startup application job resource.",
      "requirement": "optional"
    },
    "process": {
      "description": "The startup application process resource.",
      "requirement": "optional"
    }
  },
  "constraints": {
    "just_one": [
      "driver",
      "job",
      "process"
    ]
  }
}

=== ocsf/ocsf-schema/objects/reporter.json
{
  "caption": "Reporter",
  "description": "The entity from which an event or finding was first reported.",
  "extends": "_entity",
  "name": "reporter",
  "attributes": {
    "hostname": {
      "description": "The hostname of the entity from which the event or finding was first reported.",
      "requirement": "recommended"
    },
    "ip": {
      "description": "The IP address of the entity from which the event or finding was first reported.",
      "requirement": "recommended"
    }
  },
  "constraints": {
    "at_least_one": [
      "hostname",
      "ip",
      "name",
      "uid"
    ]
  }
}

=== ocsf/ocsf-schema/objects/occurrence_details.json
{
  "caption": "Occurrence Details",
  "description": "Details about where in the target entity, specified information was discovered. Only the attributes, relevant to the target entity type should be populated.",
  "extends": "object",
  "name": "occurrence_details",
  "attributes": {
    "cell_name": {
      "description": "The cell name/reference in a spreadsheet. e.g <code>A2</code>",
      "requirement": "recommended"
    },
    "column_name": {
      "description": "The column name in a spreadsheet, where the information was discovered.",
      "requirement": "recommended"
    },
    "column_number": {
      "description": "The column number in a spreadsheet or a plain text document, where the information was discovered.",
      "requirement": "recommended"
    },
    "end_line": {
      "description": "The line number of the last line of the file, where the information was discovered.",
      "requirement": "recommended"
    },
    "json_path": {
      "description": "The JSON path of the attribute in a json record, where the information was discovered",
      "requirement": "recommended"
    },
    "page_number": {
      "description": "The page number in a document, where the information was discovered.",
      "requirement": "recommended"
    },
    "record_index_in_array": {
      "description": "The index of the record in the array of records, where the information was discovered. e.g. the index of a record in an array of JSON records in a file.",
      "requirement": "recommended"
    },
    "row_number": {
      "description": "The row number in a spreadsheet, where the information was discovered.",
      "requirement": "recommended"
    },
    "start_line": {
      "description": "The line number of the first line of the file, where the information was discovered.",
      "requirement": "recommended"
    }
  },
  "constraints": {
    "at_least_one": [
      "cell_name",
      "column_name",
      "column_number",
      "end_line",
      "json_path",
      "page_number",
      "record_index_in_array",
      "row_number",
      "start_line"
    ]
  }
}

=== ocsf/ocsf-schema/extensions/linux/objects/process.json
{
  "caption": "Linux Process",
  "description": "Extends the process object to add Linux specific fields",
  "extends": "process",
  "attributes": {
    "$include": [
      "profiles/linux_users.json"
    ],
    "cgroup": {
      "requirement": "recommended"
    }
  },
  "profiles": [
    "linux/linux_users"
  ]
}

=== ocsf/ocsf-schema/objects/endpoint_connection.json
{
  "caption": "Endpoint Connection",
  "description": "The Endpoint Connection object contains information detailing a connection attempt to an endpoint.",
  "extends": "object",
  "name": "endpoint_connection",
  "attributes": {
    "code": {
      "caption": "Response Code",
      "description": "A numerical response status code providing details about the connection.",
      "requirement": "recommended"
    },
    "network_endpoint": {
      "description": "Provides characteristics of the network endpoint.",
      "requirement": "recommended"
    }
  },
  "constraints": {
    "at_least_one": [
      "network_endpoint",
      "code"
    ]
  }
}
