=== ocsf/ocsf-schema/metaschema/common-event-object.schema.json
{
    "$id": "https://schema.ocsf.io/common-event-object.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Object",
    "description": "Common metaschema shared between objects and event classes.",
    "type": "object",
    "anyOf": [
        {
            "required": [
                "description",
                "caption",
                "name",
                "attributes"
            ]
        },
        {
            "required": [
                "extends"
            ]
        }
    ],
    "properties": {
        "@deprecated": {
            "$ref": "deprecated.schema.json"
        },
        "description": {
          "type": "string",
          "description": "A concise description of the object."
        },
        "caption": {
          "type": "string",
          "description": "A short, human friendly name for the object."
        },
        "name": {
          "type": "string",
          "description": "A name of the object. It must be a unique name. The name is all lower case letters, combine words using underscore.",
          "pattern": "^[a-z0-9_]*$"
        },
        "extends": {
            "type": "string",
            "description": "An object that this one extends from."
        },
        "constraints": {
            "type": "object",
            "description": "Constraints that apply to the attribute requirements.",
            "properties": {
                "at_least_one": {
                    "type": "array",
                    "items": {"type": "string"}
                },
                "just_one": {
                    "type": "array",
                    "items": {"type": "string"}
                }
            },
            "additionalProperties": false
        },
        "profiles": {
            "type": "array",
            "items": {"type": "string"},
            "description": "The list of profiles used to create the event."
        },
        "attributes": {
            "type": "object",
            "description": "A dictionary of attributes for the object.",
            "properties": {
                "$include": {
                    "description": "A reference to another schema for attributes to include.",
                    "type": "array",
                    "items": {
                        "type": "string",
                        "format": "uri-reference"
                    }
                }
            },
            "patternProperties": {
                "^[a-z0-9_]*$": {
                    "$ref": "attribute.schema.json"
                }
            },
            "additionalProperties": false
        }
    }
}

=== ocsf/ocsf-schema/objects/data_classification.json
{
  "caption": "Data Classification",
  "description": "The Data Classification object includes information about data classification levels and data category types.",
  "extends": "object",
  "name": "data_classification",
  "attributes": {
    "category": {
      "description": "The name of the data classification category that data matched into, e.g. Financial, Personal, Governmental, etc.",
      "requirement": "optional"
    },
    "category_id": {
      "description": "The normalized identifier of the data classification category.",
      "requirement": "recommended",
      "enum": {
        "0": {
          "caption": "Unknown",
          "description": "The type is not mapped. See the <code>data_type</code> attribute, which contains a data source specific value."
        },
        "1": {
          "caption": "Personal",
          "description": "Any Personally Identifiable Information (PII), Electronic Personal Health Information (ePHI), or similarly personal information. E.g., full name, home address, date of birth, etc."
        },
        "2": {
          "caption": "Governmental",
          "description": "Any sensitive government identification number related to a person or other classified material. E.g., Passport numbers, driver license numbers, business identification, taxation identifiers, etc."
        },
        "3": {
          "caption": "Financial",
          "description": "Any financially-related sensitive information or Cardholder Data (CHD). E.g., banking account numbers, credit card numbers, International Banking Account Numbers (IBAN), SWIFT codes, etc."
        },
        "4": {
          "caption": "Business",
          "description": "Any business-specific sensitive data such as intellectual property, trademarks, copyrights, human resource data, Board of Directors meeting minutes, and similar."
        },
        "5": {
          "caption": "Military and Law Enforcement",
          "description": "Any mission-specific sensitive data for military, law enforcement, or other government agencies such as specifically classified data, weapon systems information, or other planning data."
        },
        "6": {
          "caption": "Security",
          "description": "Any sensitive security-related data such as passwords, passkeys, IP addresses, API keys, credentials and similar secrets. E.g., AWS Access Secret Key, SaaS API Keys, user passwords, database credentials, etc."
        },
        "99": {
          "caption": "Other",
          "description": "Any other type of data classification or a multi-variate classification made up of several other classification categories."
        }
      }
    },
    "classifier_details": {
      "requirement": "recommended"
    },
    "confidentiality": {
      "requirement": "optional"
    },
    "confidentiality_id": {
      "requirement": "recommended"
    },
    "discovery_details": {
      "description": "Details about the data discovered by classification job.",
      "requirement": "optional"
    },
    "policy": {
      "description": "Details about the data policy that governs data handling and security measures related to classification.",
      "requirement": "optional"
    },
    "size": {
      "description": "Size of the data classified.",
      "requirement": "optional"
    },
    "src_url": {
      "description": "The source URL pointing towards the full classifcation job details.",
      "requirement": "optional"
    },
    "status": {
      "description": "The resultant status of the classification job normalized to the caption of the <code>status_id</code> value. In the case of 'Other', it is defined by the event source.",
      "requirement": "recommended"
    },
    "status_details": {
      "description": "The contextual description of the <code>status, status_id</code> value.",
      "requirement": "optional"
    },
    "status_id": {
      "description": "The normalized status identifier of the classification job.",
      "requirement": "recommended",
      "enum": {
        "0": {
          "caption": "Unknown"
        },
        "1": {
          "caption": "Complete",
          "description": "The classification job completed for the evaluated resource."
        },
        "2": {
          "caption": "Partial",
          "description": "The classification job partially completed for the evaluated resource."
        },
        "3": {
          "caption": "Fail",
          "description": "The classification job failed for the evaluated resource."
        },
        "99": {
          "caption": "Other",
          "description": "The classification job type id is not mapped."
        }
      }
    },
    "total": {
      "description": "The total count of discovered entities, by the classification job.",
      "requirement": "optional"
    },
    "uid": {
      "description": "The unique identifier of the classification job.",
      "requirement": "optional"
    }
  },
  "constraints": {
    "at_least_one": [
      "category_id",
      "confidentiality_id"
    ]
  }
}
